### ISSUE TITLE
Why not SegWit?

### ISSUE THREAD

**Issue by bitjson** [bitjson/pmv3#2]
(Moving this from a Telegram discussion: https://t.me/c/1387982580/16531)

I initially started working on a [segwit](https://en.wikipedia.org/wiki/SegWit) proposal to enable fixed-size inductive proofs, but I haven't found any segwit strategies which seem competitive against this "hashed witnesses" idea.

Top of mind: I'm not convinced it's a good idea to fully remove signature data from any transactions. It's not necessary for any applications I've thought about, so just being conservative, I prefer to avoid it.

Practical stuff: depending on how we try to do segwit, it's likely more wasteful than hashed witnesses. Only a tiny fraction of transactions should ever need hashed witnesses, and usually only for a single input. It costs 32 extra bytes per hash, so other transactions shouldn't want to use it, and we also don't want nodes/miners to waste time/space hashing witness data for any other inputs. So a segwit strategy would only be competitive if we figure out how to make it both optional per-input and not cost unecessary hashing for nodes. Beyond that, a separate segwit merkle tree branch also makes SPV proofs up to twice as expensive for those transactions.

All that to say: even if we hypothetically deployed hashed witnesses now and segwit later, I think CashTokens would still use hashed witnesses because they'll be more efficient.

And on deployment: moving the witness data completely out of transactions would require both a change to transactions and changes to the block merkle root, which is probably a lot bigger than adding a new transaction version.

**Comment by zander** [comment]
SegWit, especially as a soft-fork, incurs a metric-ton of technical debt on all layers of the stack which is such a bad proposition that if you ask early Bitcoin Cash devs why they forked off when they did it is because we wanted to avoid segwit.

Now, stealing some core ideas and finding a sane implementation model for that is an idea nobody is against, but I doubt you need to defend the "why not segwit?" question to the average BCH devs.

**Comment by bitjson** [comment]
Ya, I think this is well-enough documented in the CHIP now (just added a new [`One TXID Per Transaction`](https://github.com/bitjson/pmv3#one-txid-per-transaction) section which makes it even clearer). With detached signatures also clearing the way for signature aggregation (which the SegWit chains won't be supporting any time soon), I think we can safely close this issue. 👍
