### ISSUE TITLE
Explanation of how PoW protects detached data.

### ISSUE THREAD

**Issue by zander** [bitjson/pmv3#7]
We talked about this in a recent video chat and I feel this may be useful to have written down.

The original Satoshi design stated that proof of work covers every single byte in the blockchain. The method for this are hash-pointers.

A hashpointer is where an object gets a crypto-graphic hash applied to it to create a static-size but unique ID of the contents of that object. The inclusion of this hash refers to the object by pointing to its unique content.
The important property is that any change in the object will break this pointer, and thus we can state that contents pointed to by a hashpointer is immutable.

In the blockheader we point to the previous blockheader by hashpointer, thereby making the historical chain immutable. We also include a merkle-root which is a more complex version of the same concept and each transaction-hash is included in this merkle-root.
As such, the entire block is covered by hashpointers and immutability because the TXID covers the entire transaction.

**Add Detached proofs**.

Making data detached has as main reason the removal of some data from the TXID. The side-effect then is that the assurance that proof of work covers it should be amended in order to not have a regression.

A regression would be that a full node that downloaded data from some random peer on the Internet could not differentiate between the block being altered after it was mined, or that the miner mined an invalid block.

The idea that PMv3 suggests is that proofs are moved outside of the TxID covered area, in exchange it replace the output-script with a hashpointer to the deteched proof.

The effect is that;

1. calculating the TXiD is made slightly harder, it isn't simply the entire transaction anymore, but slightly less.
2. The part that is not covered by the TXID is hashed anyway (approx same amount is hashed in total) but to verify it the full node has to refer to the list of outputs in order to resolve its validity.  
  The most likely algo is one that takes all hashpointers from the outputs, sorts them and then walks over the detached proofs sorting them one by one and matching their hashes to the index in the sorted list. Result; no duplicate reads, just the cost of storing and sorting a list of hashpointers equal in size to the number of inputs.

There are various small increases of complexity and cost, like any additional layer of indirectoin, the benefit is reduction of higher level data.  
So while I wrote a lot here that just means I thought through the steps, I'm not implying that any of this is bad or out of proportion. A full node doing the implementation should be made aware of this requirement, though. In order to continue to be able to detect false data vs bad block.

**Comment by bitjson** [comment]
Hey @zander, thanks so much for this write-up! I made a few more tweaks in #9 which I'm hoping make the PoW security part clearer, e.g. snippets in relevant locations like `(Detached proof integrity is guaranteed by the hash in any inputs referencing detached proofs.)` and  `Though the TXID preimage does not re-include the Detached Signature Count, Detached Signatures, Detached Proof Count, or Detached Proofs fields (which are committed to within Transaction Inputs) [...]`.

So those changes might help to clarify security for people reading the spec. Do you think we also need to describe in more detail how full nodes should do that validation? (I'm definitely open to having a sort of recommended implementation section for it. 👍)
